variables:
  SC_API_VERSION: '1.0.3'
  TARGET_SC_BRANCH: develop
  TOUCHFREE_VERSION: 'alpha5'
  UNITY_HUB: "C:/Program Files/Unity Hub/Unity Hub.exe"
  UNITY_PROJECT_PATH: $CI_PROJECT_DIR/TouchFree

stages:
  - build
  - package

TouchFree::build:
  stage: build
  when: always
  script:
    # Get Unity version and changeset from the project.
    - $line = Get-Content  $UNITY_PROJECT_PATH/ProjectSettings/ProjectVersion.txt | Select -Index 1
    - $UNITY_VERSION = $line -Split " " | Select -Index 1
    - $UNITY_CHANGESET = $line -Match '\((.+)\)' | ForEach-Object { $Matches[1] }

    # Check whether the required Unity version is installed. If not, install it.
    - Start-Process -Wait -RedirectStandardOutput "tmp.txt" -FilePath "$UNITY_HUB" -ArgumentList "-- --headless editors --installed"
    - Get-Content "tmp.txt"
    - Start-Process -Wait -RedirectStandardOutput "tmp.txt" -FilePath "$UNITY_HUB" -ArgumentList "-- --headless install-path --set C:/Unity"
    - Get-Content "tmp.txt"
    - if (-not (Test-Path "C:/Unity/$UNITY_VERSION")) { Start-Process -Wait -RedirectStandardOutput "tmp.txt" -FilePath "$UNITY_HUB" -ArgumentList "-- --headless install --version $UNITY_VERSION --changeset $UNITY_CHANGESET" }
    - Get-Content "tmp.txt"

    - $UNITY_EXE = "C:/Unity/$UNITY_VERSION/Editor/Unity.exe"
    - echo "$UNITY_EXE"

    # Update Version.txt with latest information before packaging
    - python ./Scripts/UpdateVersionFile.py --path ${env:UNITY_PROJECT_PATH}/Assets/TouchFree/Version.txt --apiVer ${env:SC_API_VERSION} --swVer ${env:TOUCHFREE_VERSION} --ref ${env:CI_COMMIT_SHORT_SHA}

    # Copy Version.txt to Client_Release folder
    - if (Test-Path -Path "./TouchFree_Build") {
        Remove-Item -LiteralPath ./TouchFree_Build -Force -Recurse
        Remove-Item -LiteralPath ./TouchFree_Build -Force -Recurse
      }
    - mkdir ./TouchFree_Build
    - cp ${env:CI_PROJECT_DIR}/TouchFree/Assets/TouchFree/Version.txt ./Client_Release

    # Build TouchFree
    - cd ./Scripts
    - "& ./build_touchfree.bat $UNITY_EXE"
  artifacts:
    name: "TouchFree_Build_${env:CI_COMMIT_SHORT_SHA}"
    paths:
      - ./Build/*
      - ./TouchFree_build.log
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10

TouchFree::package:
  stage: package
  dependencies:
    - TouchFree::build
  needs: [ "TouchFree::build" ]
  script:
    # Acquire package from SC repo using TARGET_SC_BRANCH
    # unzip it
    # Copy TouchFree Build alongside all the SC Stuff

    # Run innosetup
    - cd ./Scripts/
    - "& ./compile_installer.bat $CI_PROJECT_DIR/ScreenControl_Service_Utilities/Installer/SC_Service_Installer.iss"

    # Sign the installer with the UltraLeap certificate
    - $cert=Get-ChildItem -Path Cert:\LocalMachine\My -CodeSigningCert
    - ls $CI_PROJECT_DIR/Build
    - Set-AuthenticodeSignature -FilePath "$CI_PROJECT_DIR/Installer_Build/ScreenControl_Service_1.0.0_${SC_SRV_VERSION}_Installer.exe" -TimestampServer 'http://timestamp.comodoca.com/authenticode' -Certificate $cert
  artifacts:
    name: "TouchFree_${TOUCHFREE_VERSION}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - ./Installer_Build/*.exe
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10
